jobs:
  generate-playlist:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 添加此行，确保拥有对内容的写权限

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install yt-dlp and ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip ffmpeg
          pip3 install yt-dlp

      - name: Confirm yt-dlp and ffmpeg installation
        run: |
          which yt-dlp
          which ffmpeg

      - name: Run youtube.php
        run: php youtube.php

      - name: List directory content
        run: ls -la

      - name: Display content of playlist.m3u
        run: cat playlist.m3u || echo 'playlist.m3u 不存在'

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add playlist.m3u
          git commit -m 'Update playlist.m3u'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
