name: Update Ytdianbo M3U File

on:
  schedule:
    - cron: '0 0 */10 * *' # 每10天运行一次
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'

      - name: Install yt-dlp
        run: sudo apt-get update && sudo apt-get install -y yt-dlp

      - name: Run youtube.php
        run: php ./youtube.php

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ytdianbo.m3u
          git commit -m "Update ytdianbo.m3u file"
          git push
