name: Update YouTube Playlist M3U

on:
  schedule:
    - cron: '0 0 */10 * *' # 每隔10天运行一次
  workflow_dispatch: # 允许手动触发工作流

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # 你可以根据需要调整 PHP 版本

      - name: Install yt-dlp
        run: |
          sudo apt-get update 
          sudo apt-get install -y yt-dlp 
          python3 -m pip install --upgrade yt-dlp

      - name: Run youtube.php
        run: |
          php youtube.php > ytdianbo.m3u 
          # 输出日志以及生成的 m3u 文件内容
          echo "内容: ytdianbo.m3u"
          if [ -f ytdianbo.m3u ]; then
              cat ytdianbo.m3u
          else
              echo "ytdianbo.m3u 文件未生成"
          fi

          echo "日志: cache/yt_dl_log.txt"
          if [ -f cache/yt_dl_log.txt ]; then
              cat cache/yt_dl_log.txt
          else
              echo "cache/yt_dl_log.txt 文件未生成"
          fi

      - name: Configure git for main repo
        run: |
          git config --local user.email "gxia7466@gmail.com"
          git config --local user.name "xiatian0502"

      - name: Commit and push changes if any to main repo
        run: |
          git add ytdianbo.m3u cache/*
          git commit -m "Automatic update" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main

      - name: Clone target repo
        run: |
          git clone https://xiatian0502:${{ secrets.YYYY }}@github.com/xiatian0502/public-playlist.git
          cd public-playlist
          git checkout -b update-mytvfree || git checkout update-mytvfree
          cp ../ytdianbo.m3u .

      - name: Configure git for target repo
        working-directory: public-playlist
        run: |
          git config --local user.email "gxia7466@gmail.com"
          git config --local user.name "xiatian0502"

      - name: Stash uncommitted changes
        working-directory: public-playlist
        run: git stash || echo "Nothing to stash"

      - name: Pull and rebase changes in target repo
        working-directory: public-playlist
        run: git pull origin update-mytvfree --rebase

      - name: Apply stashed changes
        working-directory: public-playlist
        run: git stash pop || echo "Nothing to apply"

      - name: Resolve conflicts if any
        working-directory: public-playlist
        run: |
          if git ls-files -u | grep ytdianbo.m3u; then
            git checkout --theirs ytdianbo.m3u
            git add ytdianbo.m3u
            git commit -m "Resolve conflict in ytdianbo.m3u with theirs"
          fi

      - name: Commit and push changes to target repo
        working-directory: public-playlist
        run: |
          git add ytdianbo.m3u
          git commit -m 'Update ytdianbo.m3u' || echo "No changes to commit"
          git pull origin update-mytvfree --rebase
          git push origin update-mytvfree
