name: Update YouTube Playlist M3U

on:
  schedule:
    - cron: '0 0 */10 * *' # 每隔10天运行一次
  workflow_dispatch: # 允许手动触发工作流

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # 你可以根据需要调整 PHP 版本

      - name: Install yt-dlp
        run: |
          sudo apt-get update 
          sudo apt-get install -y yt-dlp
          python3 -m pip install --upgrade yt-dlp

      - name: Run youtube.php
        run: |
          php youtube.php > ytdianbo.m3u 
          # 输出日志以及生成的 m3u 文件内容
          echo "内容: ytdianbo.m3u"
          if [ -f ytdianbo.m3u ]; then
              cat ytdianbo.m3u
          else
              echo "ytdianbo.m3u 文件未生成"
          fi

          echo "日志: cache/yt_dl_log.txt"
          if [ -f cache/yt_dl_log.txt ]; then
              cat cache/yt_dl_log.txt
          else
              echo "cache/yt_dl_log.txt 文件未生成"
          fi

      - name: Configure git
        run: |
          git config --global user.email "gxia7466@gmail.com"
          git config --global user.name "xiatian0502"

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Add and commit changes
        run: |
          git add ytdianbo.m3u cache/*
          # Check if there are any changes to commit
          git diff-index --quiet HEAD || git commit -m "Update ytdianbo.m3u"

      - name: Push changes
        run: |
          git push origin HEAD:main

      - name: Verify M3U File
        run: |
          # 验证是否内容正确
          echo "验证M3U文件内容:"
          if [ -f ytdianbo.m3u ]; then
              cat ytdianbo.m3u
          else
              echo "未找到ytdianbo.m3u 文件"
              exit 1
          fi

      - name: Push to public repository
        env:
          PUBLIC0PLAYLIST: ${{ secrets.PUBLIC0PLAYLIST }}
        run: |
          git clone https://xiatian0502:${{ secrets.PUBLIC0PLAYLIST }}@github.com/xiatian0502/public-playlist.git /tmp/public-playlist
          # 更新 public-playlist 仓库中的 ytdianbo.m3u 文件
          cp ytdianbo.m3u /tmp/public-playlist/
          cd /tmp/public-playlist
          git config --global user.email "gxia7466@gmail.com"
          git config --global user.name "xiatian0502"
          git checkout update-mytvfree
          git add ytdianbo.m3u
          git commit -m "Update ytdianbo.m3u"
          git push https://xiatian0502:${{ secrets.PUBLIC0PLAYLIST }}@github.com/xiatian0502/public-playlist.git update-mytvfree
