name: Update YouTube Playlist M3U

on:
  schedule:
    - cron: '0 0 */10 * *' # 每隔10天运行一次
  workflow_dispatch: # 允许手动触发工作流

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # 你可以根据需要调整 PHP 版本

      - name: Install yt-dlp
        run: sudo apt-get update && sudo apt-get install -y yt-dlp

      - name: Run youtube.php
        run: |
          php youtube.php > ytdianbo.m3u 
          # 输出日志以及生成的 m3u 文件内容
          echo "内容: ytdianbo.m3u"
          cat ytdianbo.m3u
          echo "日志: cache/yt_dl_log.txt"
          cat cache/yt_dl_log.txt

      - name: Configure git
        run: |
          git config --global user.email "gxia7466@gmail.com"
          git config --global user.name "xiatian0502"

      - name: Fetch latest changes and rebase
        run: |
          git fetch origin
          git rebase origin/main

      - name: Add and commit changes
        run: |
          git add ytdianbo.m3u cache/*
          # Check if there are any changes to commit
          git diff-index --quiet HEAD || git commit -m "Update ytdianbo.m3u"

      - name: Push changes
        run: |
          git pull origin main --rebase
          git push origin HEAD:main
